baseURL = "https://elecbrandy.github.io/"
title = "Elecbrandy"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "The Archive at the End of the www"
  copyright = "Copyright © 2023 elecbrandy"
  dark = "auto"
  highlight = true
  mainSections = ["swift", "sesac"]

[menu]
  [[menu.main]]
    identifier = "tags"
    name = "tags"
    title = "tags"
    url = "/tags/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

[markup.tableOfContents]
  endLevel = 3
  ordered = true
  startLevel = 2

