baseURL = 'https://elecbrandy.github.io/'
languageCode = 'en-us'
title = 'home'
theme = 'freshpink'
contentDir = "content"


[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'TAGS'
pageRef = '/tags'
weight = 20

[[menus.main]]
name = 'ABOUT'
pageRef = '/about'
weight = 30

[module]
  [module.hugoVersion]
    extended = true
    min = "0.116.0"

[params]
  githubUsername = "elecbrandy"
  copyright = "Copyright © 2024 elecbrandy"

[taxonomies]
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[sitemap]
  changefreq = "daily"
  priority = 0.5


