baseURL = 'https://elecbrandy.github.io/'
languageCode = 'en-us'
title = 'Elecbrandy'

theme = "freshpink"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# robots.txt
enableRobotsTXT = true

# sitemap 생성
[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5
